// Mocks generated by Mockito 5.2.0 from annotations
// in big_toe_mobile/test/models/game.model_test.dart.
// Do not manually edit this file.

import 'package:big_toe_mobile/src/models/prompt.model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePrompt_0 extends _i1.Fake implements _i2.Prompt {}

/// A class which mocks [Prompt].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrompt extends _i1.Mock implements _i2.Prompt {
  MockPrompt() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get text =>
      (super.noSuchMethod(Invocation.getter(#text), returnValue: '') as String);
  @override
  Set<String> get tags =>
      (super.noSuchMethod(Invocation.getter(#tags), returnValue: <String>{})
          as Set<String>);
  @override
  _i2.Prompt setTags(Set<String>? newTags) =>
      (super.noSuchMethod(Invocation.method(#setTags, [newTags]),
          returnValue: _FakePrompt_0()) as _i2.Prompt);
  @override
  _i2.Prompt setText(String? newText) =>
      (super.noSuchMethod(Invocation.method(#setText, [newText]),
          returnValue: _FakePrompt_0()) as _i2.Prompt);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i2.Prompt formatPrompt(Set<String>? players) =>
      (super.noSuchMethod(Invocation.method(#formatPrompt, [players]),
          returnValue: _FakePrompt_0()) as _i2.Prompt);
}
